### PR TITLE
Added distance() filter with tests

### PR DESCRIPTION
**Pull request by kkomelin**
Please review.

### CODE REVIEW

**Comment by basemkhirat** [comment]
Thanks @kkomelin to your efforts.
Travis CI build seems to be not passed. please fix build with php7 and php7.1 and I will merge the PR.
See [build](https://travis-ci.org/basemkhirat/elasticsearch/builds/204104893).

**Comment by kkomelin** [comment]
Thanks @basemkhirat. I will investigate the issue with Travis.

**Comment by kkomelin** [comment]
@basemkhirat First of all, I'd like to ask if we really need all minor PHP 5.6 versions support? https://github.com/basemkhirat/elasticsearch/blob/master/.travis.yml#L3
I suggest leaving 5.6.30 only because there are probably no dramatic changes between these minor versions. Moreover, it will significantly reduce the Travis checks time.
Will commit this change in a few minutes.

**Comment by kkomelin** [comment]
@basemkhirat Tests are passed on all PHP versions but not on hhvm. Do we really need hhvm support?

**Comment by basemkhirat** [comment]
@kkomelin we can exclude hhvm in the current time.

**Comment by kkomelin** [comment]
@basemkhirat Thanks.

**Pull request merged**
